bot_prefix: "PREFIX"
token: "BOT_TOKEN"
application_id: "APPLICATION_ID"
owners:
  - OWNER_ID
blacklist:
  - 000000000000000000
main_color: 0xD75BF4
error: 0xE02B2B
success: 0x42F56C
warning: 0xF59E42
info: 0x4299F5